// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugbaxpjguksqjeyteetc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnYmF4cGpndWtzcWpleXRlZXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzkxNjUsImV4cCI6MjA2MDQxNTE2NX0.98Qg1k6aFLCcBty9Xj1cd4A8sKxOW25g-n4fe1h7iSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);